# Pull base image
FROM python:3.11

#Copy project

WORKDIR /app

#Install requirements.txt
COPY ./requirements.txt .
RUN pip install -r requirements.txt

#Copy entrypoint script
COPY ./entrypoint.sh .
RUN ["chmod", "+x", "/app/entrypoint.sh"]


#Set entrypoint
ENTRYPOINT ["sh", "/app/entrypoint.sh"]