version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: gunicorn --timeout=20 ReadMore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
    restart: always
    env_file:
      - .env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=nuriaguapa
      - POSTGRES_DB=djangodb
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
volumes:
  postgres_data: