# fly.toml app configuration file generated for webproject-readmore on 2023-05-21T13:40:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "webproject-readmore"
primary_region = "mad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"